version: '3'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      - DATABASE_URL=postgresql://doadmin:AVNS_TK6mL23WhT_WWMdxG7P@db-postgresql-blr1-30615-do-user-17467981-0.m.db.ondigitalocean.com:25060/defaultdb?sslmode=require?sslcert=ca-certificate.crt
      - API_PORT=3000
      - SWAGGER_ENABLE=1
      - API_PREFIX=/api/v1
      - JWT_SECRET=secret
      - JWT_ISSUER=nestjs
      - HEALTH_TOKEN=health
      - PASSENGERS_ALLOWED=yes
    restart: always
    networks:
      - webnet

networks:
  webnet:
