name: Docker CI/CD Pipeline

# Xác định sự kiện trigger cho pipeline, trong trường hợp này là push lên nhánh develop
on:
  push:
    branches:
      - main

# Định nghĩa các jobs cần thực hiện 
jobs:
   # Job 1: build và test
   # Job thực thi trên máy ảo ubuntu
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
        uses: actions/checkout@v2

      - name: Login to Docker Hub
          # Sử dụng action "docker/login-action" để đăng nhập vào Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and test
        # Build và test image được build ra bằng Docker 
        run: |
          docker build -t karl .

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        # Sử dụng action "docker/build-push-action" để đẩy image lên Docker Hub
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/karl:${{ github.sha }}

 # Job 2: Deploy
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
       # Sử dụng action "appleboy/ssh-action" để triển khai image lên server thông qua SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
              # Pull image mà được push lên DockerHub bên trên
              docker pull ${{ secrets.DOCKER_USERNAME }}/karl:${{ github.sha }}

              # Dừng và gỡ bỏ container hiện tại (nếu có)
              docker stop karl-container
              docker rm karl-container 

              docker run -d \
                -p 80:3000 \
                --name karl-container \
                -e DATABASE_URL=${{secrets.DB_URL}} \
                -e API_PORT=3000 \
                -e SWAGGER_ENABLE=1 \
                -e API_PREFIX=/api/v1 \
                -e JWT_SECRET=secret \
                -e JWT_ISSUER=nestjs \
                -e HEALTH_TOKEN=health \
                -e PASSENGERS_ALLOWED=yes \
                -e HOST_URL = "${{secrets.HOST_URL}}" \
                ${{ secrets.DOCKER_USERNAME }}/karl:${{ github.sha }}


